package by.topolev.config;

public class Validators {
	public static final String ENTERED_FILENAME_EXTANSION_VALIDATOR = "ENTERED_FILENAME_EXTANSION_VALIDATOR";
	public static final String UPLOAD_FILENAME_EXTANSION_VALIDATOR = "UPLOAD_FILENAME_EXTANSION_VALIDATOR";
	public static final String UNIQUE_FILENAME_VALIDATOR = "UNIQUE_FILENAME_VALIDATOR";
}
